project_id = "ivvcefmzejilpxkksymt"

[functions.sync-profile]
verify_jwt = false

[functions.claim-task]
verify_jwt = false

[functions.spin-wheel]
verify_jwt = false

[functions.admin-action]
verify_jwt = false

[functions.get-room-info]
verify_jwt = false
